Business managements
Restazo/business.api pull request #10
Opened 2024-03-26 19:32 UTC by Matheus-OAMK

Register / Login / Logout features
Delete Business Feature

2024-03-26 21:32 UTC, RepoRover commented on src/controllers/authentication.ts
getSession and logOut endpoints are missing the error log if try-catch block catches the error

2024-03-26 21:34 UTC, RepoRover commented on src/data/business.ts
Here instead of using console.error() you used console.log() to log an error

2024-03-26 21:35 UTC, RepoRover commented on src/controllers/business.ts
Here instead of using console.error() you used console.log() to log an error

2024-03-26 21:38 UTC, RepoRover commented on src/lib/register-business.ts
Here instead of using console.error() you used console.log() to log an error

2024-03-26 21:46 UTC, RepoRover commented on src/middleware/deserializeUser.ts
If I understood this code right, you use this middleware before request hits any of the endpoints. You always let the request to pass to the endpoint, so if the endpoint is protected, you check for req.user existence, and if so you let if pass next, if no you return error "invalid session"

2024-03-26 21:49 UTC, RepoRover commented on src/controllers/authentication.ts
You check for req.user in getSession, when you actually already check for it in "protect" middleware before it reaches getSession

2024-03-26 21:50 UTC, RepoRover commented on src/controllers/business.ts
You check for req.user in deleteBusiness when you have already checked that in "protect" middleware before it reaches to deleteBusiness

2024-03-26 21:52 UTC, RepoRover requested changes
Very well done! I love the code, just should make a few adjustments

2024-03-27 00:00 UTC, Matheus-OAMK commented on src/controllers/business.ts
Typescript doesn't recognize it. Thats why I check again

2024-03-27 11:59 UTC, Matheus-OAMK commented on src/controllers/business.ts
Fixed the issue

2024-03-27 12:10 UTC, RepoRover approved these changes
Very well done!

2024-03-27 12:10 UTC, merged