Feature/restaurant profile management
Restazo/business.api pull request #23
Opened 2024-04-12 13:09 UTC by Matheus-OAMK

2024-04-12 22:13 UTC, RepoRover commented
Currently I can upload new cover and new logo, but if old logo/cover has different extension than the new file extension, old one stays on the place and new one uploads
![Screenshot 2024-04-13 at 1 06 13](https://github.com/Restazo/business.api/assets/143033820/0439552a-9630-4f46-a6d6-ee43e41a92a9)

2024-04-12 22:17 UTC, RepoRover requested changes

2024-04-12 23:47 UTC, Matheus-OAMK commented on src/controllers/authentication.ts
In the case of a wrong password or invalid email when trying to sign in. It is best to send a generic message "invalid email or password" for security reasons.

2024-04-13 01:24 UTC, Matheus-OAMK commented
Closed this pull request. Opened a new pull request into feature/restaurant-profile-management addressing these issues.

2024-04-13 11:16 UTC, RepoRover approved these changes

2024-04-13 11:16 UTC, merged